### ISSUE TITLE
Плохая идея позиционировать этот элемент. Лучше сделать через float

### ISSUE THREAD

**Issue by igosheva** [RomaTur/loftschool#24]
https://github.com/RomaTur/loftschool/blob/84d070e161429e997f4881b263a76e4be989b9df/sites/coworking/css/style.less#L253

**Comment by RomaTur** [comment]
покажи как сделать через float, совсем не понимаю

**Comment by igosheva** [comment]
Сделал вроде уже одинаковыми колонками, такой вариант подходит)
