### ISSUE TITLE
Добавить для ссылки класс, href и перенеси стили с привязкой к классу

### ISSUE THREAD

**Issue by igosheva** [RomaTur/loftschool#26]
https://github.com/RomaTur/loftschool/blob/84d070e161429e997f4881b263a76e4be989b9df/sites/coworking/main/index.html#L144

**Comment by RomaTur** [comment]
@igosheva что значит перевести стили с привязкой к классу?

**Comment by igosheva** [comment]
Имела ввиду, что если есть стили, которые ты задаешь тегам  нужно их перенести классам этих элементов)
