### ISSUE TITLE
Никаких br между блоками, перенос можно сделать за счет display:block к блоку, который нужно перенести на другую строку

### ISSUE THREAD

**Issue by igosheva** [RomaTur/loftschool#3]
https://github.com/RomaTur/loftschool/blob/cf7c26a0a1b73f038db0000c42cdaec450293a11/sites/coworking/rates/index.html#L26

**Comment by RomaTur** [comment]
@igosheva  к тексту могу применять br?

**Comment by igosheva** [comment]
да, к тексту в индивидуальных случаях (когда без них нельзя никак) можно)
