### ISSUE TITLE
Лишняя обертка div

### ISSUE THREAD

**Issue by igosheva** [RomaTur/loftschool#9]
https://github.com/RomaTur/loftschool/blob/cf7c26a0a1b73f038db0000c42cdaec450293a11/sites/coworking/rates/index.html#L93

**Comment by RomaTur** [comment]
@igosheva , это фоновый цвет поверх картинки, overlay :anguished:
Я добавил уже классы для наглядности.

![С](https://user-images.githubusercontent.com/22766671/30666586-80ffe168-9e5d-11e7-87d5-a8c6b36d1703.png)
![Без](https://user-images.githubusercontent.com/22766671/30666593-873a1eea-9e5d-11e7-933f-badf9977712b.png)

**Comment by igosheva** [comment]
Классов не увидела, там стили прописаны вот так .schedule__item-title>div

**Comment by igosheva** [comment]
А это грубая ошибка, так как я неоднократно говорила, что в тегам стили мы не добавляем.
